:PACKAGE: ast

dict 1.0 :LIBRARY: dtclose.c dtdisc.c dtflatten.c dthash.c dtmethod.c \
	dtopen.c dtsize.c dtrestore.c dtstat.c dttree.c dtview.c dtwalk.c \
	dtextract.c

$(INCLUDEDIR):INSTALLDIR: dict.h
