The/DT/The list/NN/list of/IN/of laboratories/NNS/laboratory claiming/VBG/claim to/TO/to be/VB/be producing/VBG/produce inexplicable/JJ/inexplicable amounts/NNS/amount of/IN/of heat/NN/heat from/IN/from "/"/" cold/JJ/cold fusion/NN/fusion "/"/" experiments/NNS/experiment is/VBZ/be slowly/RB/slowly growing/VBG/grow ././.
&/CC/&
But/CC/But the/DT/the experiments/NNS/experiment continue/VBP/continue to/TO/to be/VB/be plagued/VBN/plague by/IN/by lack/NN/lack of/IN/of firm/NN/firm evidence/NN/evidence that/IN/that the/DT/the extra/JJ/extra heat/NN/heat is/VBZ/be coming/VBG/come from/IN/from the/DT/the fusing/NN/fusing of/IN/of hydrogen/NN/hydrogen atoms/NNS/atom ././.
New/JJ/New experiments/NNS/experiment at/IN/at some/DT/some of/IN/of the/DT/the big/JJ/big national/JJ/national laboratories/NNS/laboratory are/VBP/be still/RB/still unable/JJ/unable to/TO/to find/VB/find hints/NNS/hint of/IN/of nuclear/JJ/nuclear fusion/NN/fusion reactions/NNS/reaction ,/,/, leaving/VBG/leave only/RB/only the/DT/the finding/NN/finding of/IN/of tritium/NN/tritium in/IN/in a/DT/a Texas/NNP/Texas experiment/NN/experiment to/TO/to support/VB/support University/NNP/University of/IN/of Utah/NNP/Utah chemists/NNS/chemist '/POS/' claim/NN/claim of/IN/of achieving/VBG/achieve hydrogen/NN/hydrogen fusion/NN/fusion at/IN/at room/NN/room temperatures/NNS/temperature ././.
&/CC/&
The/DT/The latest/JJS/late developments/NNS/development in/IN/in cold/JJ/cold fusion/NN/fusion research/NN/research were/VBD/be presented/VBN/present in/IN/in 24/CD/24 reports/NNS/report delivered/VBN/deliver at/IN/at the/DT/the fall/NN/fall meeting/NN/meeting here/RB/here of/IN/of the/DT/the Electrochemical/NNP/Electrochemical Society/NNP/Society ,/,/, the/DT/the first/JJ/first scientific/JJ/scientific meeting/NN/meeting in/IN/in five/CD/five months/NNS/month to/TO/to hear/VB/hear formal/JJ/formal reports/NNS/report on/IN/on cold/JJ/cold fusion/NN/fusion experiments/NNS/experiment ././.
&/CC/&
The/DT/The meeting/NN/meeting offered/VBD/offer stark/JJ/stark evidence/NN/evidence of/IN/of a/DT/a dramatic/JJ/dramatic fall/NN/fall in/IN/in scientific/JJ/scientific interest/NN/interest in/IN/in cold/JJ/cold fusion/NN/fusion research/NN/research ././.
Of/IN/Of the/DT/the 1,300/CD/1,300 chemists/NNS/chemist registered/VBN/register for/IN/for the/DT/the society/NN/society 's/POS/'s weeklong/JJ/weeklong meeting/NN/meeting ,/,/, fewer/JJR/few than/IN/than 200/CD/200 sat/VBD/sit through/IN/through the/DT/the day/NN/day and/CC/and a/DT/a half/NN/half of/IN/of cold/JJ/cold fusion/NN/fusion presentations/NNS/presentation at/IN/at week/NN/week 's/POS/'s end/NN/end ././.
This/DT/This was/VBD/be in/IN/in contrast/NN/contrast with/IN/with the/DT/the society/NN/society 's/POS/'s meeting/NN/meeting last/JJ/last May/NNP/May ,/,/, at/IN/at the/DT/the height/NN/height of/IN/of the/DT/the controversy/NN/controversy ,/,/, when/WRB/when more/JJR/more than/IN/than 1,500/CD/1,500 scientists/NNS/scientist ,/,/, along/IN/along with/IN/with scores/NNS/score of/IN/of reporters/NNS/reporter and/CC/and TV/NN/TV crews/NNS/crew ,/,/, crowded/VBN/crowd into/IN/into a/DT/a Los/NNP/Los Angeles/NNP/Angeles hotel/NN/hotel ballroom/NN/ballroom for/IN/for a/DT/a tumultuous/JJ/tumultuous special/JJ/special night/NN/night session/NN/session on/IN/on the/DT/the subject/NN/subject ././.
&/CC/&
Neither/CC/Neither of/IN/of the/DT/the two/CD/two chemists/NNS/chemist whose/WP$/whose Utah/NNP/Utah experiments/NNS/experiment triggered/VBD/trigger the/DT/the cold/JJ/cold fusion/NN/fusion uproar/NN/uproar ,/,/, Martin/NNP/Martin Fleischmann/NNP/Fleischmann and/CC/and B./NNP/B. Stanley/NNP/Stanley Pons/NNP/Pons ,/,/, were/VBD/be at/IN/at the/DT/the meeting/NN/meeting ././.
But/CC/But some/DT/some members/NNS/member of/IN/of an/DT/an ad/NN/ad hoc/FW/hoc expert/NN/expert committee/NN/committee set/VBN/set up/IN/up by/IN/by the/DT/the Department/NNP/Department of/IN/of Energy/NNP/Energy to/TO/to evaluate/VB/evaluate the/DT/the cold/JJ/cold fusion/NN/fusion research/NN/research were/VBD/be in/IN/in the/DT/the audience/NN/audience ././.
The/DT/The committee/NN/committee is/VBZ/be to/TO/to recommend/VB/recommend at/IN/at the/DT/the end/NN/end of/IN/of the/DT/the month/NN/month whether/IN/whether DOE/NNP/DOE should/MD/should support/VB/support cold/JJ/cold fusion/NN/fusion research/NN/research ././.
&/CC/&
Most/JJS/Most of/IN/of the/DT/the two/CD/two dozen/NN/dozen scientists/NNS/scientist taking/VBG/take the/DT/the podium/NN/podium reported/VBD/report results/NNS/result with/IN/with new/JJ/new ,/,/, more/RBR/more sophisticated/JJ/sophisticated variations/NNS/variation of/IN/of the/DT/the seemingly/RB/seemingly simple/JJ/simple electrolysis/NN/electrolysis -/:/- of/IN/of -/:/- water/NN/water experiments/NNS/experiment described/VBD/describe last/JJ/last March/NNP/March by/IN/by Messrs/NNPS/Messrs ././.
Fleischmann/NNP/Fleischmann and/CC/and Pons/NNP/Pons ././.
The/DT/The experiments/NNS/experiment involve/VBP/involve encircling/VBG/encircle a/DT/a thin/JJ/thin rod/NN/rod of/IN/of palladium/NN/palladium metal/NN/metal with/IN/with a/DT/a wire/NN/wire of/IN/of platinum/NN/platinum and/CC/and plunging/VBG/plunge the/DT/the two/CD/two electrodes/NNS/electrode into/IN/into "/"/" heavy/JJ/heavy "/"/" water/NN/water in/IN/in which/WDT/which the/DT/the hydrogen/NN/hydrogen atoms/NNS/atom are/VBP/be a/DT/a doubly/RB/doubly heavy/JJ/heavy form/NN/form known/VBN/know as/IN/as deuterium/NN/deuterium ././.
When/WRB/When an/DT/an electric/JJ/electric current/NN/current is/VBZ/be applied/VBN/apply to/TO/to the/DT/the palladium/NN/palladium and/CC/and platinum/NN/platinum electrodes/NNS/electrode ,/,/, the/DT/the heavy/JJ/heavy water/NN/water did/VBD/do begin/VB/begin to/TO/to break/VB/break up/IN/up ,/,/, or/CC/or dissociate/VB/dissociate ././.
Ordinarily/RB/Ordinarily the/DT/the electrolysis/NN/electrolysis ,/,/, or/CC/or breakup/NN/breakup ,/,/, of/IN/of the/DT/the water/NN/water would/MD/would consume/VB/consume almost/RB/almost all/DT/all of/IN/of the/DT/the electrical/JJ/electrical energy/NN/energy ././.
But/CC/But Messrs/NNPS/Messrs ././.
Fleischmann/NNP/Fleischmann and/CC/and Pons/NNP/Pons said/VBD/say their/PRP$/their experiments/NNS/experiment also/RB/also produced/VBN/produce large/JJ/large amounts/NNS/amount of/IN/of heat/NN/heat ././.
The/DT/The heat/NN/heat energy/NN/energy plus/CC/plus the/DT/the energy/NN/energy consumed/VBN/consume by/IN/by the/DT/the breakup/NN/breakup of/IN/of the/DT/the water/NN/water molecules/NNS/molecule added/VBD/add to/TO/to far/RB/far more/JJR/more energy/NN/energy coming/VBG/come out/IN/out of/IN/of the/DT/the apparatus/NN/apparatus than/IN/than electrical/JJ/electrical energy/NN/energy going/VBG/go in/IN/in ,/,/, they/PRP/they reported/VBD/report ././.
Because/IN/Because they/PRP/they also/RB/also detected/VBD/detect tritium/NN/tritium and/CC/and indications/NNS/indication of/IN/of nuclear/JJ/nuclear radiation/NN/radiation ,/,/, they/PRP/they asserted/VBD/assert that/IN/that the/DT/the "/"/" excess/JJ/excess "/"/" heat/NN/heat energy/NN/energy must/MD/must be/VB/be coming/VBG/come from/IN/from energy/NN/energy released/VBN/release by/IN/by the/DT/the nuclear/JJ/nuclear fusion/NN/fusion of/IN/of deuterium/NN/deuterium atoms/NNS/atom inside/IN/inside the/DT/the palladium/NN/palladium rod/NN/rod ././.
&/CC/&
As/IN/As of/IN/of last/JJ/last weekend/NN/weekend ,/,/, a/DT/a dozen/NN/dozen labs/NNS/lab also/RB/also have/VBP/have reported/VBN/report measuring/VBG/measure "/"/" excess/JJ/excess "/"/" heat/NN/heat from/IN/from similar/JJ/similar electrolytic/JJ/electrolytic experiments/NNS/experiment ,/,/, although/IN/although amounts/NNS/amount of/IN/of such/JJ/such heat/NN/heat vary/VBP/vary widely/RB/widely ././.
One/CD/One of/IN/of the/DT/the seven/CD/seven reports/NNS/report presented/VBN/present here/RB/here of/IN/of excess/JJ/excess heat/NN/heat production/NN/production was/VBD/be given/VBN/give by/IN/by Richard/NNP/Richard A./NNP/A. Oriani/NNP/Oriani ,/,/, professor/NN/professor of/IN/of chemical/NN/chemical engineering/NN/engineering at/IN/at the/DT/the University/NNP/University of/IN/of Minnesota/NNP/Minnesota ././.
&/CC/&
Mr./NNP/Mr. Oriani/NNP/Oriani said/VBD/say his/PRP$/his skepticism/NN/skepticism of/IN/of the/DT/the Utah/NNP/Utah claims/NNS/claim was/VBD/be initially/RB/initially confirmed/VBN/confirm when/WRB/when his/PRP$/his first/JJ/first experiments/NNS/experiment last/JJ/last spring/NN/spring failed/VBD/fail to/TO/to produce/VB/produce results/NNS/result ././.
But/CC/But he/PRP/he then/RB/then borrowed/VBD/borrow a/DT/a palladium/NN/palladium rod/NN/rod from/IN/from chemists/NNS/chemist at/IN/at Texas/NNP/Texas A&M/NNP/A&M who/WP/who said/VBD/say they/PRP/they were/VBD/be getting/VBG/get excess/JJ/excess heat/NN/heat ././.
"/"/" The/DT/The results/NNS/result were/VBD/be fascinating/JJ/fascinating ,/,/, "/"/" he/PRP/he said/VBD/say ././.
On/IN/On the/DT/the fourth/JJ/fourth "/"/" run/VB/run "/"/" with/IN/with the/DT/the borrowed/VBN/borrow rod/NN/rod ,/,/, the/DT/the experiment/NN/experiment began/VBD/begin producing/VBG/produce excess/JJ/excess heat/NN/heat ././.
The/DT/The experiment/NN/experiment was/VBD/be stopped/VBN/stop briefly/NN/briefly to/TO/to change/VB/change an/DT/an instrument/NN/instrument ././.
When/WRB/When it/PRP/it was/VBD/be restarted/VBN/restart ,/,/, heat/NN/heat output/NN/output "/"/" really/RB/really took/VBD/take off/IN/off "/"/" and/CC/and produced/VBN/produce excess/JJ/excess heat/NN/heat for/IN/for several/JJ/several hours/NNS/hour before/IN/before dying/VBG/die down/RB/down ,/,/, he/PRP/he said/VBD/say ././.
&/CC/&
Typical/JJ/Typical of/IN/of other/JJ/other experiments/NNS/experiment ,/,/, Mr./NNP/Mr. Oriani/NNP/Oriani said/VBD/say his/PRP$/his experiment/NN/experiment was/VBD/be "/"/" very/RB/very erratic./JJ/erratic. "/"/"
It/PRP/It would/MD/would go/VB/go along/IN/along doing/VBG/do nothing/NN/nothing but/CC/but dissociating/VBG/dissociate the/DT/the heavy/JJ/heavy water/NN/water and/CC/and then/RB/then at/IN/at totally/RB/totally unpredictable/JJ/unpredictable times/NNS/time ,/,/, it/PRP/it would/MD/would begin/VB/begin producing/VBG/produce excess/JJ/excess heat/NN/heat for/IN/for as/RB/as long/RB/long as/IN/as 10/CD/10 or/CC/or 11/CD/11 hours/NNS/hour before/IN/before quieting/VBG/quiet down/RB/down ././.
The/DT/The excess/JJ/excess heat/NN/heat was/VBD/be 15%/CD/15% to/TO/to 20%/CD/20% more/JJR/more than/IN/than the/DT/the energy/NN/energy involved/VBN/involve in/IN/in the/DT/the electrolysis/NN/electrolysis of/IN/of water/NN/water ././.
&/CC/&
Mr./NNP/Mr. Oriani/NNP/Oriani said/VBD/say the/DT/the heat/NN/heat bursts/NNS/burst were/VBD/be too/RB/too large/JJ/large and/CC/and too/RB/too long/JJ/long to/TO/to be/VB/be explained/VBN/explain by/IN/by the/DT/the sudden/JJ/sudden release/NN/release of/IN/of energy/NN/energy that/WDT/that might/MD/might have/VB/have slowly/RB/slowly accumulated/VBN/accumulate during/IN/during the/DT/the experiments/NNS/experiment '/POS/' quiescent/JJ/quiescent times/NNS/time ,/,/, as/IN/as some/DT/some scientists/NNS/scientist have/VBP/have suggested/VBN/suggest ././.
"/"/" There/EX/There is/VBZ/be a/DT/a reality/NN/reality to/TO/to the/DT/the excess/JJ/excess energy/NN/energy ,/,/, "/"/" he/PRP/he said/VBD/say ././.
&/CC/&
Other/JJ/Other scientists/NNS/scientist said/VBD/say they/PRP/they also/RB/also were/VBD/be getting/VBG/get sporadic/JJ/sporadic bursts/NNS/burst of/IN/of excess/JJ/excess heat/NN/heat lasting/VBG/last several/JJ/several hours/NNS/hour at/IN/at a/DT/a time/NN/time ././.
The/DT/The bursts/NNS/burst often/RB/often occur/VBP/occur ,/,/, they/PRP/they said/VBD/say ,/,/, after/IN/after they/PRP/they "/"/" perturbed/JJ/perturbed "/"/" the/DT/the experiments/NNS/experiment by/IN/by raising/VBG/raise or/CC/or lowering/VBG/lower the/DT/the amount/NN/amount of/IN/of electric/JJ/electric current/JJ/current being/NN/being applied/VBN/apply ,/,/, or/CC/or switching/VBG/switch the/DT/the current/NN/current off/IN/off and/CC/and on/RB/on ././.
One/CD/One chemist/NN/chemist privately/RB/privately suggested/VBD/suggest this/DT/this hinted/VBD/hint that/IN/that some/DT/some "/"/" anomalous/JJ/anomalous "/"/" chemical/NN/chemical reactions/NNS/reaction might/MD/might be/VB/be producing/VBG/produce the/DT/the heat/NN/heat ././.
&/CC/&
One/CD/One reason/NN/reason questions/NNS/question surround/VBP/surround the/DT/the heat/NN/heat experiments/NNS/experiment is/VBZ/be that/IN/that they/PRP/they involve/VBP/involve unusually/RB/unusually meticulous/JJ/meticulous measurements/NNS/measurement ././.
Typically/RB/Typically ,/,/, the/DT/the input/NN/input energy/NN/energy ranges/NNS/range from/IN/from a/DT/a third/JJ/third of/IN/of a/DT/a watt/NN/watt to/TO/to one/CD/one watt/NN/watt and/CC/and the/DT/the excess/JJ/excess energy/NN/energy is/VBZ/be measured/VBN/measure in/IN/in tenths/NNS/tenth of/IN/of a/DT/a watt/NN/watt ././.
One/CD/One exception/NN/exception is/VBZ/be a/DT/a continuing/VBG/continue experiment/NN/experiment at/IN/at Stanford/NNP/Stanford University/NNP/University where/WRB/where as/RB/as much/JJ/much as/IN/as 10/CD/10 watts/NNS/watt of/IN/of energy/NN/energy are/VBP/be being/VBG/be put/VB/put into/IN/into the/DT/the electrolytic/JJ/electrolytic cells/NNS/cell ././.
A/DT/A cell/NN/cell filled/VBN/fill with/IN/with heavy/JJ/heavy water/NN/water is/VBZ/be producing/VBG/produce 1.0/CD/1.0 to/TO/to 1.5/CD/1.5 watts/NNS/watt more/JJR/more heat/NN/heat than/IN/than an/DT/an identical/JJ/identical electrolytic/JJ/electrolytic cell/NN/cell filled/VBN/fill with/IN/with ordinary/JJ/ordinary water/NN/water next/JJ/next to/TO/to it/PRP/it ,/,/, reported/VBD/report Turgut/NNP/Turgut M./NNP/M. Gur/NNP/Gur ,/,/, an/DT/an associate/NN/associate of/IN/of materials/NNS/material scientist/NN/scientist Robert/NNP/Robert A./NNP/A. Huggins/NNP/Huggins ,/,/, head/NN/head of/IN/of the/DT/the Stanford/NNP/Stanford experimental/JJ/experimental team/NN/team ././.
&/CC/&
One/CD/One of/IN/of the/DT/the few/JJ/few hints/NNS/hint the/DT/the excess/JJ/excess heat/NN/heat might/MD/might be/VB/be produced/VBN/produce by/IN/by fusion/NN/fusion came/VBD/come from/IN/from brief/JJ/brief remarks/NNS/remark by/IN/by chemist/NN/chemist John/NNP/John Bockris/NNP/Bockris of/IN/of Texas/NNP/Texas A&M/NNP/A&M University/NNP/University ././.
Mr./NNP/Mr. Bockris/NNP/Bockris previously/RB/previously reported/VBD/report getting/VBG/get bursts/NNS/burst of/IN/of excess/JJ/excess heat/NN/heat and/CC/and of/IN/of detecting/VBG/detect increasing/VBG/increase amounts/NNS/amount of/IN/of tritium/NN/tritium forming/VBG/form in/IN/in the/DT/the heavy/JJ/heavy water/NN/water ././.
He/PRP/He said/VBD/say that/IN/that within/IN/within the/DT/the past/JJ/past few/JJ/few days/NNS/day ,/,/, he/PRP/he 's/VBZ/'s gotten/VBN/get evidence/NN/evidence that/IN/that there/EX/there is/VBZ/be a/DT/a "/"/" weak/JJ/weak correlation/NN/correlation "/"/" between/IN/between the/DT/the time/NN/time the/DT/the heat/NN/heat bursts/NNS/burst occur/VBP/occur and/CC/and the/DT/the production/NN/production of/IN/of tritium/NN/tritium ././.
There/EX/There is/VBZ/be not/RB/not any/DT/any way/NN/way to/TO/to continuously/RB/continuously measure/VBP/measure the/DT/the amount/NN/amount of/IN/of tritium/NN/tritium in/IN/in the/DT/the heavy/JJ/heavy water/NN/water ,/,/, so/IN/so it/PRP/it 's/VBZ/'s been/VBN/be difficult/JJ/difficult to/TO/to tell/VB/tell whether/IN/whether the/DT/the tritium/NN/tritium formation/NN/formation is/VBZ/be related/VBN/relate to/TO/to the/DT/the heat/NN/heat bursts/NNS/burst or/CC/or some/DT/some other/JJ/other phenomenon/NN/phenomenon ././.
&/CC/&
Increasingly/RB/Increasingly careful/JJ/careful attempts/NNS/attempt to/TO/to measure/VB/measure neutrons/NNS/neutron ,/,/, which/WDT/which would/MD/would be/VB/be strong/JJ/strong evidence/NN/evidence of/IN/of fusion/NN/fusion reactions/NNS/reaction ,/,/, continue/VB/continue to/TO/to be/VB/be negative/JJ/negative ././.
Messrs/NNPS/Messrs ././.
Fleischmann/NNP/Fleischmann and/CC/and Pons/NNP/Pons initially/RB/initially reported/VBD/report indirect/JJ/indirect evidence/NN/evidence of/IN/of neutrons/NNS/neutron being/VBG/be produced/VBN/produce in/IN/in their/PRP$/their experiment/NN/experiment but/CC/but later/RB/later conceded/VBD/concede the/DT/the measurements/NNS/measurement were/VBD/be questionable/JJ/questionable ././.
Researchers/NNS/researcher at/IN/at Sandia/NNP/Sandia National/NNP/National Laboratories/NNPS/laboratory in/IN/in Albuquerque/NNP/Albuquerque ,/,/, N.M./NNP/N.M. ,/,/, reported/VBD/report they/PRP/they went/VBD/go so/RB/so far/RB/far as/IN/as to/TO/to take/VB/take a/DT/a "/"/" cold/JJ/cold fusion/NN/fusion "/"/" experiment/NN/experiment and/CC/and three/CD/three neutron/NN/neutron detectors/NNS/detector into/IN/into a/DT/a tunnel/NN/tunnel under/IN/under 300/CD/300 feet/NNS/foot of/IN/of granite/NN/granite to/TO/to shield/VB/shield the/DT/the detectors/NNS/detector from/IN/from cosmic/JJ/cosmic rays/NNS/ray ././.
A/DT/A number/NN/number of/IN/of times/NNS/time they/PRP/they detected/VBD/detect neutrons/NNS/neutron in/IN/in one/CD/one ,/,/, sometimes/RB/sometimes two/CD/two ,/,/, of/IN/of the/DT/the three/CD/three detectors/NNS/detector ,/,/, but/CC/but only/RB/only once/RB/once during/IN/during 411/CD/411 hours/NNS/hour of/IN/of the/DT/the experiment/NN/experiment did/VBD/do they/PRP/they detect/VBP/detect a/DT/a neutron/NN/neutron burst/NN/burst in/IN/in all/DT/all three/CD/three detectors/NNS/detector -/:/- -/:/- and/CC/and they/PRP/they think/VBP/think that/WDT/that was/VBD/be a/DT/a spurious/JJ/spurious event/NN/event ././.
&/CC/&
Shimson/NNP/Shimson Gottesfeld/NNP/Gottesfeld of/IN/of Los/NNP/Los Alamos/NNP/alamo National/NNP/National Laboratory/NNP/Laboratory said/VBD/say researchers/NNS/researcher there/EX/there detected/VBN/detect a/DT/a burst/NN/burst of/IN/of neutrons/NNS/neutron from/IN/from an/DT/an early/JJ/early cold/JJ/cold fusion/NN/fusion experiment/NN/experiment last/JJ/last April/NNP/April but/CC/but decided/VBD/decide not/RB/not to/TO/to announce/VB/announce it/PRP/it until/IN/until they/PRP/they could/MD/could confirm/VB/confirm it/PRP/it ././.
In/IN/In subsequent/JJ/subsequent experiments/NNS/experiment ,/,/, one/CD/one of/IN/of two/CD/two neutron/NN/neutron detectors/NNS/detector occasionally/RB/occasionally indicated/VBD/indicate a/DT/a burst/NN/burst of/IN/of neutrons/NNS/neutron but/CC/but neutron/NN/neutron bursts/NNS/burst were/VBD/be never/RB/never recorded/VBN/record in/IN/in both/DT/both detectors/NNS/detector at/IN/at the/DT/the same/JJ/same time/NN/time ././.
They/PRP/They concluded/VBD/conclude the/DT/the indications/NNS/indication of/IN/of neutrons/NNS/neutron stemmed/VBD/stem from/IN/from faults/NNS/fault in/IN/in the/DT/the detectors/NNS/detector rather/RB/rather than/IN/than from/IN/from the/DT/the cold/JJ/cold fusion/NN/fusion experiment/NN/experiment ././.
&/CC/&
At/IN/At the/DT/the Lawrence/NNP/Lawrence Berkeley/NNP/Berkeley Laboratory/NNP/Laboratory in/IN/in California/NNP/California ,/,/, new/JJ/new experiments/NNS/experiment indicated/VBD/indicate that/IN/that the/DT/the lithium/NN/lithium added/VBD/add to/TO/to the/DT/the heavy/JJ/heavy water/NN/water so/IN/so it/PRP/it will/MD/will conduct/VB/conduct a/DT/a current/NN/current can/MD/can produce/VB/produce previously/RB/previously unsuspected/JJ/unsuspected electrical/JJ/electrical effects/NNS/effect on/IN/on the/DT/the surface/NN/surface of/IN/of the/DT/the palladium/NN/palladium rod/NN/rod -/:/- -/:/- which/WDT/which Messrs/NNPS/Messrs ././.
Fleischmann/NNP/Fleischmann and/CC/and Pons/NNP/Pons might/MD/might have/VB/have misinterpreted/VBN/misinterpret ,/,/, reported/VBD/report Philip/NNP/Philip Ross/NNP/Ross from/IN/from the/DT/the California/NNP/California laboratory/NN/laboratory ././.
&/CC/&
