INPUT FILE :
============


``/``/`` Such/JJ/Such research/NN/research may/MD/may ultimately/RB/ultimately  result/VB/result in/IN/in the/DT/the ability/NN/ability to/TO/to
  regenerate/VB/regenerate damaged/JJ/damaged tissues/NNS/tissue or/CC/or
  to/TO/to turn/VB/turn off/RP/off genes/NNS/gene that/WDT/that cause/VBP/cause
  cancer/NN/cancer ''/''/'' or/CC/or to/TO/to regulate/VB/regulate
   genes/NNS/gene  that/WDT/that cause/VBP/cause Down/NNP/Down 's/POS/'s syndrome/NN/syndrome
  ,/,/, the/DT/the leading/VBG/lead cause/NN/cause of/IN/of mental/JJ/mental
  retardation/NN/retardation ,/,/, according/VBG/accord to/TO/to an/DT/an
  NIH/NNP/NIH summary/NN/summary ./SENT/.


COMMAND LINE :
==============
$ rules.cmp < test

!!!! the program print the following output and stuck.

input sentence: ``/``/`` Such/JJ/Such research/NN/research may/MD/may ultimately/RB/ultimately  result/VB/result in/IN/in the/DT/the ability/NN/ability to/TO/to



!!!! I attached the compiled parser !!!!

thanks.
