"/" Peaceful/JJ "/" Nuclear/NNP Explosion/NN 
China/NNP 's/POS interest/NN in/IN this/DT technology/NN 
may/MD scuttle/VB a/DT test/NN -/: ban/NN treaty/NN 
<p>/NN 
<s>/NN 1/CD China/NNP 's/POS northwest/JJ territory/NN ,/, which/WDT includes/VBZ the/DT Gobi/NNP Desert/NNP ,/, contains/VBZ almost/JJ half/NN of/IN that/DT country/NN 's/POS total/JJ landmass/NN but/CC only/RB 7/CD percent/NN of/IN its/PRP$ freshwater./JJ </s>/NN 
<s>/NN Recently/RB some/DT Chine/NNP engineer/NN proposed/VBN diverting/VBG water/NN into/IN this/DT arid/JJ area/NN from/IN the/DT mighty/JJ Brahmaputra/NNP River/NNP ,/, which/WDT skirts/VBZ China/NNP 's/POS southern/JJ border/NN before/IN dipping/VBG into/IN India/NNP and/CC Bangladesh./NNP </s>/NN 
<s>/NN Such/JJ a/DT feat/NN would/MD be/VB "/" impossible/JJ "/" with/IN conventional/JJ methods/NNS ,/, engineer/NN stated/VBN at/IN a/DT meeting/NN held/VBD last/JJ December/NNP at/IN the/DT Chine/NNP Academy/NNP of/IN Engineer/NNP Physics/NNP in/IN Beijing./NNP </s>/NN 
<s>/NN But/CC they/PRP added/VBD that/IN "/" we/PRP can/MD certainly/RB accomplish/VB this/DT project/NN "/" -/: with/IN nuclear/JJ explosion./CD </s>/NN 
<s>/VBG This/DT statement/NN is/VBZ just/RB one/CD of/IN many/JJ lately/RB in/IN which/WDT Chine/NNP technology/NN and/CC officials/NNS have/VBP touted/VBN the/DT potential/NN of/IN nuclear/JJ blast/NN for/IN carrying/VBG out/IN nonmilitary/JJ goals./CD </s>/NN 
<s>/NN Now/RB that/IN France/NNP has/VBZ finally/RB pledged/VBN to/TO stop/VB test/NN ,/, the/DT Chine/NNP interest/NN in/IN so/RB -/: called/VBN peaceful/JJ nuclear/JJ explosion/NN (/( Pne/NNP )/SYM is/VBZ emerging/VBG as/IN the/DT major/JJ obstacle/NN to/TO the/DT enactment/NN of/IN a/DT Comprehensive/NNP Test/NNP Ban/NNP Treaty/NNP ,/, which/WDT arms/NNS -/: control/NN advocates/NNS had/VBD anticipated/VBN might/MD be/VB achieved/VBN this/DT year./CD </s>/NN 
<s>/VBG The/DT U.S./NNP considers/VBZ China/NNP 's/POS position/NN on/IN Pne/NNP to/TO be/VB "/" totally/RB unacceptable/JJ ,/, "/" says/VBZ Katherine/NNP E./NNP Magraw/NNP of/IN the/DT U.S./NNP Arms/NNP Control/NNP and/CC Disarmament/NNP Agency./NNP </s>/NN 
<s>/NN "/" Other/JJ states/NNS would/MD view/VB Pne/NNP as/IN a/DT gaping/VBG loophole/NN "/" in/IN a/DT test/NN -/: ban/NN treaty/NN ,/, she/PRP maintains/VBZ ,/, because/IN any/DT nuclear/JJ blast/NN can/MD provide/VB useful/JJ information/NN for/IN military/JJ purposes./CD </s>/NN 
<s>/NN Of/IN the/DT 38/CD states/NNS engaged/VBN in/IN test/NN -/: ban/NN talks/NNS ,/, only/RB China/NNP is/VBZ seeking/VBG a/DT PNE/NNP exclusion./CD </s>/NN 
<s>/VBG Some/DT diplomat/NN fear/NN that/IN China/NNP secretly/RB intends/VBZ to/TO sabotage/VB the/DT test/NN ban/NN so/RB that/IN it/PRP can/MD upgrade/VB its/PRP$ relatively/RB small/JJ ,/, primitive/JJ nuclear/JJ arsenal/NN without/IN any/DT constraints./JJ </s>/NN 
<s>/NNP China/NNP is/VBZ thought/VBN to/TO possess/VB some/DT 300/CD warheads/NNS ,/, compared/VBN with/IN 10,000/CD in/IN the/DT U.S./NNP and/CC 12,000/CD in/IN the/DT former/JJ Russian/NNP republics./CD </s>/NN 
<s>/NNP China/NNP has/VBZ conducted/VBN 43/CD nuclear/JJ test/NN in/IN all/DT ,/, most/RBS recently/RB in/IN August/NNP 1995,/CD whereas/IN the/DT U.S./NNP and/CC Russia/NNP have/VBP detonated/VBN 1,030/CD and/CC 715/CD devices/NNS ,/, respectively./JJ </s>/NN 
<s>/NN One/CD Asian/JJ diplomat/NN with/IN close/NN ties/NNS to/TO China/NNP contends/VBZ privately/RB that/IN Beijing/NNP is/VBZ not/RB trying/VBG to/TO scuttle/VB the/DT test/NN ban/NN entirely/RB ,/, but/CC only/RB to/TO delay/VB its/PRP$ enactment/NN long/JJ enough/RB for/IN a/DT few/RB more/JJR weapons/NNS test./JJ </s>/NN 
<s>/NN "/" When/WRB push/VB comes/VBZ to/TO shove/VB ,/, "/" says/VBZ the/DT diplomat/NN ,/, the/DT Chine/NNP will/MD accept/VB a/DT test/NN ban/NN without/IN an/DT allowance/NN for/IN Pne./NNP </s>/NN 
<s>/NN But/CC Chine/NNP officials/NNS have/VBP denied/VBN that/IN they/PRP are/VBP engaging/VBG in/IN negotiating/VBG tactics./JJ </s>/NN 
<s>/NN "/" As/IN a/DT populous/JJ developing/NN country/NN with/IN insufficient/JJ energy/NN and/CC mineral/NN resources/NNS ,/, "/" declared/VBD Qian/NNP Shaojun/NNP ,/, a/DT test/NN -/: ban/NN negotiator/NN ,/, in/IN January/NNP ,/, "/" China/NNP cannot/MD abandon/VB forever/RB any/DT promising/JJ and/CC potentially/RB useful/JJ technology./JJ "/" </s>/NN 
<s>/NN To/TO alleviate/VB concerns/NNS that/IN China/NNP might/MD carry/VB out/IN weapons/NNS research/VBP under/IN the/DT guise/NN of/IN Pne/NNP ,/, Wang/NNP Xuexian/NNP ,/, deputy/NN ambassador/NN to/TO the/DT United/NNP Nations/NNPS ,/, stated/VBN in/IN February/NNP that/IN China/NNP would/MD be/VB willing/JJ to/TO accept/VB "/" stringent/JJ international/JJ monitoring/NN and/CC verification/NN with/IN prior/JJ approval/NN by/IN the/DT treaty/NN organization./JJ "/" </s>/NN 
<s>/VBG Both/DT the/DT U.S./NNP and/CC the/DT former/JJ Russian/NNP Union/NNP once/RB supported/VBD PNE/NNP program/NN .18/CD From/IN the/DT 1950s/CD through/IN 1973,/CD the/DT U.S./NNP detonated/VBD 27/CD nuclear/JJ devices/NNS in/IN Nevada/NNP ,/, Alaska/NNP ,/, New/NNP Mexico/NNP ,/, Colorado/NNP and/CC other/JJ states/NNS as/IN part/NN of/IN its/PRP$ Plowshare/NNP program/NN ;/: the/DT test/NN were/VBD aimed/VBN primarily/RB at/IN establishing/VBG the/DT efficacy/NN of/IN nuclear/JJ blast/NN for/IN the/DT stimulate/VB of/IN oil/NN and/CC gas/NN production/NN and/CC for/IN excavation./JJ (/( In/IN the/DT late/JJ 1950s/CD the/DT U.S./NNP considered/VBD blasting/VBG a/DT new/JJ canal/NN through/IN Central/NNP America/NNP with/IN Pne./NNP )/SYM </s>/NN 
<s>/VBG The/DT largest/JJS excavation/NN experiment/NN took/VBD place/NN in/IN 1962/CD at/IN the/DT Department/NNP of/IN Energy/NNP 's/POS Nevada/NNP Test/NNP Site./NNP </s>/NN 
<s>/VBG The/DT so/RB -/: called/VBN Sedan/NNP test/NN displaced/VBN 12/CD million/CD tons/NNS of/IN earth/NN ,/, creating/VBG the/DT largest/JJS man/NN -/: made/VBN crater/NN in/IN the/DT world/NN ;/: it/PRP also/RB generat/VBP a/DT "/" vast/JJ amount/NN of/IN fallout/NN "/" that/WDT drifted/VBD beyond/IN Nevada/NNP and/CC over/IN Utah/NNP ,/, according/VBG to/TO Derek/NNP S./NNP Scammell/NNP ,/, a/DT spokesperson/NN for/IN the/DT Nevada/NNP Test/NNP Site./NNP </s>/NN 
<s>/NN Explosion/NN in/IN oil/NN and/CC gas/NN fields/NNS did/VBD indeed/RB stimulate/VB production/NN ,/, but/CC in/IN some/DT cases/NNS they/PRP also/RB made/VBD the/DT fuel/NN so/RB radioactive/JJ that/IN it/PRP could/MD not/RB be/VB used./JJ </s>/NN 
<s>/VBG The/DT Plowshare/NNP program/NN was/VBD discontinued/VBN in/IN 1973/CD after/IN the/DT U.S./NNP decided/VBD that/IN the/DT cons/NNS of/IN Pne/NNP -/: -/: including/VBG criticism/NN from/IN the/DT growing/VBG environmental/JJ movement/NN -/: -/: far/RB outweighed/VBD the/DT benefits./JJ </s>/NN 
<s>/VBG The/DT Russian/NNP Union/NNP pursued/VBD a/DT much/RB more/RBR vigorous/JJ program/NN ,/, notes/NNS Milo/NNP D./NNP Nordyke/NNP of/IN Lawrence/NNP Livermore/NNP Laboratory./NNP </s>/NN 
<s>/VBG The/DT Russian/NNP detonated/VBD 124/CD Pne/NNP in/IN all/DT ,/, Nordyke/NNP says/VBZ ,/, for/IN many/JJ ends:/NN to/TO move/VB earth/NN ,/, to/TO stimulate/VB fossil/JJ -/: fuel/NN production/NN ,/, to/TO blow/VB out/IN oil/NN and/CC gas/NN fires/NNS ,/, to/TO create/VB underground/JJ cavities/NNS for/IN storing/VBG fossil/JJ fuel/NN and/CC to/TO dispose/VB of/IN toxic/JJ waste./JJ </s>/NN 
<s>/NN With/IN a/DT technique/NN called/VBD seismic/JJ sounding/NN ,/, the/DT Russian/NNP also/RB created/VBD images/NNS of/IN buried/VBN geologic/JJ formations/NNS by/IN observing/VBG how/WRB they/PRP reflect/VBP shock/NN waves/NNS from/IN nuclear/JJ explosion./CD </s>/NN 
<s>/VBG The/DT Russian/NNP only/RB reluctantly/RB agreed/VBD to/TO stop/VB their/PRP$ PNE/NNP program/NN in/IN 1988/CD as/IN a/DT result/NN of/IN then/JJ president/NNP Mikhail/NNP S./NNP Gorbachev/NNP 's/POS disarmament/NN initiative/NN ,/, Nordyke/NNP explains./VBZ </s>/NN 
<s>/NN But/CC he/PRP adds/VBZ that/IN the/DT engineer/NN involved/VBN in/IN the/DT Russian/NNP program/NN still/RB take/VB pride/NN in/IN their/PRP$ accomplishments./JJ </s>/NN 
<s>/NN Indeed/RB ,/, Robert/NNP S./NNP Norris/NNP of/IN the/DT Natural/NNP Resources/NNP Defense/NNP Council/NNP ,/, a/DT watchdog/NN group/NN ,/, speculates/VBZ that/IN China/NNP 's/POS recent/JJ interest/NN in/IN Pne/NNP may/MD have/VB been/VBN piqued/VBN by/IN "/" Russian/NNP mischief/NN -/: makers/NNS "/" who/WP pine/VBP for/IN the/DT return/NN of/IN the/DT technology./JJ </s>/NN 
<s>/NNP PNE/NNP experts/NNS from/IN the/DT Russian/NNP Ministry/NNP of/IN Nuclear/NNP Energy/NNP were/VBD active/JJ participants/NNS at/IN the/DT meeting/NN in/IN Beijing/NNP last/JJ December./NNP </s>/NN 
<s>/VBG The/DT Russian/NNP related/VBD their/PRP$ experience/NN with/IN Pne/NNP and/CC provided/VBN advice/NN and/CC encouragement/NN to/TO Chine/NNP engineer/NN formulating/VBG their/PRP$ own/JJ plans/NNS ,/, according/VBG to/TO a/DT report/NN by/IN He/PRP Zuoxiu/NNP ,/, one/CD of/IN the/DT participants./JJ </s>/NN 
<s>/VBG Those/DT plans/NNS included/VBD a/DT scheme/NN for/IN deflecting/VBG asteroids/NNS away/RB from/IN Earth/NNP with/IN nuclear/JJ -/: tipped/VBD rockets/NNS (/( an/DT idea/NN also/RB popular/JJ among/IN certain/JJ members/NNS of/IN the/DT U.S./NNP nuclear/JJ weapons/NNS establishment/NN )/SYM and/CC the/DT Brahmaputra/NNP River/NNP project/NN ,/, which/WDT would/MD require/VB blasting/VBG a/DT 20/CD -/: kilometer/NN channel/NN through/IN a/DT mountain/NN range./CD </s>/NN 
<s>/VBG The/DT Russian/NNP hailed/VBD this/DT latter/NN proposal/NN as/IN a/DT "/" wonderful/JJ idea/NN ,/, "/" He/PRP claimed./JJ </s>/NN 
<s>/NN In/IN addition/NN ,/, the/DT Chine/NNP proposed/VBD harnessing/VBG the/DT energy/NN of/IN underground/JJ thermonuclear/JJ explosion/NN for/IN generat/NN electricity/NN .34/CD The/DT explosion/NN would/MD supposedly/RB take/VB place/NN in/IN a/DT subterranean/JJ cavity/NN lined/VBN with/IN massive/JJ steel/NN tubes/NNS ,/, which/WDT would/MD conduct/VB steam/NN to/TO turbines/NNS on/IN the/DT surface/NN .35/CD "/" It/PRP 's/VBZ possible/JJ that/IN this/DT kind/NN of/IN controllable/JJ nuclear/JJ electric/JJ station/NN will/MD become/VB the/DT main/JJ energy/NN supplier/NN around/IN the/DT world/NN in/IN 30/CD to/TO 50/CD years/NNS ,/, "/" He/PRP wrote./JJ </s>/NN 
<s>/VBG That/DT scenario/NN is/VBZ highly/RB unlikely/JJ ,/, according/VBG to/TO Richard/NNP L./NNP Garwin/NNP of/IN the/DT IBM/NNP Thomas/NNP J./NNP Watson/NNP Research/NNP Center/NNP ,/, who/WP participated/VBD in/IN a/DT U.S./NNP study/NN of/IN this/DT power/NN -/: generat/VB concept/NN in/IN the/DT 1970s./CD </s>/NN 
<s>/VBG The/DT investigation/NN ,/, he/PRP says/VBZ ,/, showed/VBN that/IN a/DT minimum/NN of/IN two/CD detonations/VBZ a/DT day/NN ,/, or/CC more/JJR than/IN 700/CD a/DT year/NN ,/, would/MD be/VB required/VBN to/TO keep/VB such/JJ a/DT generat/NN running./CD </s>/NN 
<s>/VBG The/DT costs/NNS of/IN this/DT technology/NN ,/, Garwin/NNP says/VBZ ,/, would/MD exceed/VB those/DT for/IN conventional/JJ nuclear/JJ reactors/NNS ,/, which/WDT are/VBP already/RB hard/JJ -/: pressed/VBN to/TO compete/VB economically/RB with/IN hydropower/NN ,/, fossil/JJ fuel/NN and/CC other/JJ energy/NN sources./CD </s>/NN 
<s>/NNP Garwin/NNP contends/VBZ that/IN nonnuclear/NN methods/NNS are/VBP also/RB cheaper/JJR ,/, more/RBR effective/JJ and/CC less/RBR damaging/JJ to/TO the/DT environment/NN than/IN Pne/NNP for/IN applications/NNS such/JJ as/IN excavation/NN and/CC oil/NN -/: well/RB stimulate./JJ </s>/NN 
<s>/NNP Pne/NNP are/VBP simply/RB not/RB worth/JJ the/DT risk/NN that/IN they/PRP would/MD pose/VB to/TO international/JJ security/NN ,/, adds/VBZ Nordyke/NNP of/IN Lawrence/NNP Livermore./NNP </s>/NN 
<s>/NN Even/RB if/IN a/DT nation/NN is/VBZ prevented/VBN by/IN international/JJ monitors/NNS from/IN extracting/VBG detailed/VBN information/NN from/IN a/DT PNE/NNP ,/, he/PRP explains/VBZ ,/, simply/RB knowing/VBG the/DT yield/NN of/IN a/DT nuclear/JJ device/NN -/: -/: and/CC that/IN it/PRP works/VBZ -/: -/: has/VBZ military/JJ value./CD </s>/NN 
<s>/NN In/IN the/DT 1950s,/CD Nordyke/NNP recalls/VBZ ,/, arms/NNS -/: control/NN experts/NNS considered/VBN establishing/VBG an/DT international/JJ organization/NN that/WDT would/MD stockpile/VB devices/NNS for/IN Pne/NNP and/CC oversee/VB their/PRP$ use/NN to/TO ensure/VB that/IN they/PRP were/VBD not/RB exploited/VBN for/IN military/JJ advantage./JJ </s>/NN 
<s>/NN But/CC this/DT plan/NN was/VBD soon/RB abandoned/VBN as/IN politically/RB and/CC technically/RB unworkable./CD </s>/NN 
<s>/NNP Michael/NNP Krepon/NNP of/IN the/DT Henry/NNP L./NNP Stimson/NNP Center/NNP ,/, a/DT think/NN tank/NN in/IN Washington/NNP ,/, D.C./NNP ,/, is/VBZ cautiously/RB hopeful/JJ that/IN a/DT Comprehensive/NNP Test/NNP Ban/NNP Treaty/NNP can/MD still/RB be/VB achieved/VBN this/DT year/NN ,/, even/RB if/IN China/NNP continues/VBZ to/TO insist/VB on/IN a/DT loophole/NN for/IN Pne./NNP </s>/NN 
<s>/VBG The/DT trick/NN ,/, he/PRP observes/VBZ ,/, will/MD be/VB negotiating/VBG a/DT provision/NN that/WDT technically/RB allows/VBZ Pne/NNP but/CC makes/VBZ them/PRP subject/NN to/TO so/RB many/JJ restrictions/NNS that/IN they/PRP are/VBP unlikely/JJ ever/RB to/TO be/VB employed./JJ </s>/NN 
<s>/NN "/" I/PRP do/VBP not/RB believe/VB this/DT is/VBZ a/DT treaty/NN -/: breaker/NN ,/, "/" Krepon/NNP says/NNS of/IN the/DT Chine/NNP position/NN on/IN Pne./NNP </s>/NN 
<s>/NN "/" But/CC it/PRP sure/JJ as/IN hell/NN is/VBZ not/RB any/DT help./CD "/" </s>/NN 
</p>/NN 
